services:
  mongodb:
    image: mongo:latest
    container_name: fb-backend-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - fb-backend-network

  mongo-express:
    image: mongo-express:latest
    container_name: fb-backend-mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongodb:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongodb
    networks:
      - fb-backend-network

volumes:
  mongodb_data:
    name: fb-backend-mongodb-data

networks:
  fb-backend-network:
    driver: bridge